services:
  php:
    environment:
      # db.php uses $_ENV for dsn (data source name).
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      # TODO set 0 in production
      PHP_ENABLE_XDEBUG: 1
    depends_on:
      - mysql
    build: .
    volumes:
      # TODO what the point if this folder is empty
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '${APP_PORT}:80'

  mysql:
    image: mysql:8.0
    volumes:
      - ../mysql:/var/lib/mysql:delegated
      # - ../mysql_etc:/etc:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
