services:
  php:
    environment:
      # db.php uses $_ENV for dsn (data source name).
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_ENABLE_XDEBUG: 1
    depends_on:
      - mysql
    build: .
    # image: yiisoftware/yii2-php:8.3-fpm-nginx
    volumes:
      # TODO what the point if this folder is empty
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
      - '9005:9005' # xdebug

  mysql:
    # image: container-registry.oracle.com/mysql/community-server
    image: mysql:8.0
    volumes:
      - ../mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
