FROM yiisoftware/yii2-php:8.3-fpm-nginx

# TODO uncomment in production
# RUN cd /app && php yii migrate --interactive=0

# upd: turned out that xdebug works well even without this cfg.
# COPY xdebug.ini /usr/local/etc/php/conf.d/