services:
  app:
    environment:
      # TODO looks redundant
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    build: .
    # image: yiisoftware/yii2-php:8.3-fpm-nginx
    volumes:
      # TODO what the point if this folder is empty
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    # image: container-registry.oracle.com/mysql/community-server
    image: mysql:8.0
    volumes:
      - ../db/mysql:/var/lib/mysql:delegated
    # it doesn't work
    # hostname: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3307:3306'
