LOCK TABLES `goods_category` WRITE;
INSERT INTO `goods_category` VALUES (4,'diptera', 'diptera'),(2,'dragonflies', 'dragonflies'),(5,'lepidoptera', 'lepidoptera'),(1,'orthoptera', 'orthoptera'),(6,'spiders', 'spiders'),(3,'stick insects', 'stick-insects');
UNLOCK TABLES;

LOCK TABLES `unit_of_goods` WRITE;
INSERT INTO `unit_of_goods` VALUES 
(1,'Danaida monarch','Such a butterflies love flowers. They can\'t fly directly (as i\'d been observing), but they are orange sometimes.','u',1,3,5,1,39, 'danaida-monarch'),
(2,'Firefly','This dude emits light at night.','u',10,30,4,1,79, 'firefly'),
(3,'Goliath Birdeater','The biggest spider on the earth. This means it huge. Such a spiders live in ordinary houses around the whole planet in mouse style: at summer they go to forests to hunt and then, by winter, they come in our\'s, usual people\'s houses and winter somewhere close to your bed. They wake up at night and touch your food for fun, covering up tracks. If you are afraid of them quite much, you should buy one. This can be explained this way: the hut may have only one this spider as an owner, so if you already have your hand spider in cage, then you have nothing to be afraid of. These spiders can\'t stand each other, so the spider-alien will leave your hut.','u',1,183502,1,1,8390, 'goliath-birdeater'),
(4,'Heteropteryx dilatata','Heteropteryx is a monotypic genus of stick insects containing Heteropteryx dilatata as the only described species and gives its name to the family of the Heteropterygidae. Their only species may be known as jungle nymph, Malaysian stick insect, Malaysian wood nymph, Malayan jungle nymph, or Malayan wood nymph and because of their size it is commonly kept in zoological institutions and private terrariums of insect lovers. It originates from the Malay Archipelago and is nocturnal.','u',1,50,3,1,590, 'heteropteryx-dilatata'),
(5,'Master Mantis','Widely known actor from \"Kong Fu Panda\"','u',1,1,3,1,3299, 'master-mantis'),
(6,'Mosquitoes box','This set of mosquitoes may save your life in case you owe the box of mosquitoes to somebody who threaten you with death. Also you can use it to feed some birds like sinitsa or vorobay or even popolzen\'.','g',200,3,4,0,159, 'mosquitoes-box'),
(8,'Grasshopper','Found in fields and meadows, these insects can jump great distances.','g',25,78,2,0,48, 'grasshopper'),
(9,'Cicada','Known for their loud buzzing sound, cicadas emerge periodically.','u',32,189,1,1,97, 'cicada'),
(10,'Dragonfly','Graceful fliers, dragonflies are often seen near bodies of water.','g',41,203,6,0,126, 'dragonfly'),
(11,'Moth','Nocturnal relatives of butterflies, moths are attracted to light.','u',53,354,3,1,165, 'moth'),
(12,'Ant','Social insects living in large colonies, ants are industrious workers.','g',65,102,4,0,194, 'ant'),
(13,'Beetle','Hard-shelled insects, beetles come in a variety of shapes and sizes.','u',77,255,5,1,223, 'beetle'),
(14,'Cricket','Known for their chirping sounds, crickets are common in gardens.','g',89,406,2,0,252, 'cricket'),
(15,'Butterfly','Colorful insects that undergo metamorphosis from caterpillars.','u',101,457,1,1,281, 'butterfly'),
(16,'Praying Mantis','Predatory insects with distinctive front legs, mantises are fascinating.','g',113,508,6,0,310, 'praying-mantis'),
(17,'Fly','Common household pests, flies reproduce quickly and can be annoying.','u',125,559,3,1,339, 'fly'),
(18,'Wasp','Stinging insects, wasps can be aggressive when disturbed.','g',137,610,4,0,368, 'wasp'),
(19,'Centipede','Many-legged creatures, centipedes are fast-moving and can bite.','u',149,661,5,1,397, 'centipede'),
(20,'Millipede','Similar to centipedes but slower, millipedes curl up when threatened.','g',161,712,2,0,426, 'millipede'),
(21,'Scorpion','Venomous arachnids with a stinger tail, scorpions are found in deserts.','u',173,763,1,1,455, 'scorpion'),
(22,'Earwig','Named for their appearance, earwigs have pincers on their rear end.','g',185,814,6,0,484, 'earwig'),
(23,'Termite','Wood-eating insects that form large colonies, termites can damage structures.','u',197,865,3,1,513, 'termite'),
(24,'Flea','Parasitic insects that feed on blood, fleas are tiny and hard to see.','g',209,916,4,0,542, 'flea'),
(25,'Bed Bug','Nocturnal parasites that feed on human blood, bed bugs are difficult to eradicate.','u',221,967,5,1,571, 'bed-bug'),
(26,'Locust','Swarming insects that can devastate crops, locusts are a type of grasshopper.','g',233,1018,2,0,600, 'locust'),
(27,'Water Strider','Insects that skim across the surface of water, appearing to walk on it.','u',245,1069,1,1,629, 'water-strider'),
(28,'Mayfly','Short-lived insects that spend most of their lives as aquatic larvae.','g',257,1120,6,0,658, 'mayfly'),
(29,'Stick Insect','Camouflaged to look like twigs, stick insects blend into their environment.','u',269,1171,3,1,687, 'stick-insect'),
(30,'Lacewing','Beneficial insects that prey on aphids and other small pests.','g',281,1222,4,0,716, 'lacewing'),
(31,'Velvet Ant','Wingless female wasps with brightly colored fur-like bodies.','u',293,1273,5,1,745, 'velvet-ant'),
(32,'Walking Stick','Another camouflaged insect, walking sticks resemble thin branches.','g',305,1324,2,0,774, 'walking-stick'),
(33,'Assassin Bug','Predatory insects that ambush and kill other insects.','u',317,1375,1,1,803, 'assassin-bug'),
(34,'Stonefly','Aquatic insects that live in clean, cold streams and rivers.','g',329,1426,6,0,832, 'stonefly'),
(35,'Damselfly','Closely related to dragonflies, damselflies are slender and delicate.','u',341,1477,3,1,861, 'damselfly'),
(36,'Leafhopper','Jumping insects that feed on plant sap, leafhoppers can transmit diseases.','g',353,1528,4,0,890, 'leafhopper'),
(37,'Webworm','Caterpillars that spin webs in trees, webworms can defoliate plants.','u',365,1579,5,1,919, 'webworm'),
(38,'Pill Bug','Also called roly-polies, pill bugs roll into balls when disturbed.','g',377,1630,2,0,948, 'pill-bug'),
(39,'Springtail','Minute insects that leap using a spring-like appendage.','u',389,1681,1,1,977, 'springtail'),
(40,'Thrips','Tiny insects that feed on plant tissues, thrips can cause damage to crops.','g',401,1732,6,0,1006, 'thrips'),
(41,'Silverfish','Nocturnal insects that feed on paper and fabric, silverfish are common pests.','u',413,1783,3,1,1035, 'silverfish'),
(42,'Booklouse','Similar to silverfish, booklice infest stored grains and books.','g',425,1834,4,0,1064, 'booklouse'),
(43,'Mealybug','Scaly insects that suck plant juices, mealybugs can weaken plants.','u',437,1885,5,1,1093, 'mealybug'),
(44,'Spider Mite','Microscopic pests that spin webs on plants, spider mites can cause yellowing.','g',449,1936,2,0,1122, 'spider-mite'),
(45,'Hornworm','Large caterpillars that feed on tomato plants, hornworms can decimate crops.','u',461,1987,1,1,1151, 'hornworm'),
(46,'Stink Bug','Insects that emit a foul odor when threatened, stink bugs can damage fruits.','g',473,2038,6,0,1180, 'stink-bug'),
(47,'Sawfly Larva','Caterpillar-like insects that feed on leaves, sawfly larvae can defoliate trees.','u',485,2089,3,1,1209, 'sawfly-larva');
UNLOCK TABLES;