services:
  php:
    container_name: php-app
    build: .
    volumes:
      # TODO what the point if this folder is empty
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - "./:/app:delegated"
    environment:
      # db.php uses $_ENV for dsn (data source name).
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # DB_OUTER_PORT: ${DB_OUTER_PORT} # app doesn't need it
      # TODO set 0 in production
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    depends_on:
      mysql:
        condition: "service_healthy"
    ports:
      - "${APP_PORT}:80"

  mysql:
    container_name: mysql-db
    image: mysql:8.0
    # image: mariadb:10.4.22
    volumes:
      - "../mysql:/var/lib/mysql:delegated"
      # - ../mysql_etc:/etc:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"
      interval: "5s"
      retries: 10
    # ports:
    #   - '${DB_OUTER_PORT}:3306' # https://stackoverflow.com/questions/78803793/docker-compose-service-cannot-connect-to-other-services-in-docker-compose

  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: ${DB_HOST}
    depends_on:
      mysql:
        condition: "service_healthy"
    ports:
      - "8080:80"
  
  swagger:
    container_name: swagger
    image: docker.swagger.io/swaggerapi/swagger-ui
    volumes:
      - "./api docs:/usr/share/nginx/html/swagger"
    environment:
      SWAGGER_JSON: "/usr/share/nginx/html/swagger/swagger.json"
      # API_URL: "http://localhost:${APP_PORT}" # the url on the main page
    ports:
      - "8082:8080"

